dataset_params:
  input_file_path: "data/raw/heart_cleveland_upload.csv"
  output_paths:
    - "data/processed/train.csv"
    - "data/processed/val.csv"

splitting_params:
  val_size: 0.2
  random_state: null

preprocessing_params:
  pipeline:
    - "normalization"
    - "polynomial"

feature_params:
  categorical_features:
    - 'sex'
    - 'restecg'
    - 'slope'
    - 'fbs'
    - 'cp'
    - 'exang'
    - 'thal'
    - 'ca'
  numerical_features:
    - 'age'
    - 'oldpeak'
    - 'trestbps'
    - 'thalach'
    - 'chol'
  target_col: "condition"

model_params:
  model_save_path:
    "models/logistic_regression_model.pkl"
  model_name:
    "LogisticRegression"
  parameters:
    # C
    - 1
    # class_weight
    - "balanced"
    # dual
    - false
    # fit_intercept
    - true
    # intercept_scaling
    - 1
    # l1-ratio
    - null
    # max_iter
    - 100
    # multi_class
    - false
    # n_jobs
    - null
    # penalty
    - "l2"
    # random_state
    - null
    # solver
    - "lbfgs"
    # tol
    - 1e-4
    # verbose
    - 0.3
    # warm_start
    - false
